version: "3.9"

services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: restaurant_pos_api
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./apps/api/.env
    networks:
      - restaurant_pos_network

  dashboard:
    build:
      context: ./apps/dashboard-web
      dockerfile: Dockerfile
    container_name: restaurant_pos_dashboard
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - ./apps/dashboard-web/.env
    depends_on:
      - api
    networks:
      - restaurant_pos_network

networks:
  restaurant_pos_network:
    driver: bridge